django项目/school/forclass/urls.py
from django.conf.urls import url

from forclass import views

urlpatterns=[
    url(r"^hellow/",views.hellow,name="hellow"),

    # 用户管理

    url(r"^register/",views.register,name="register"),
    url(r"^checkusername/",views.check_username,name="checkusername"),
    url(r"^checkphone/",views.check_phone,name="checkphone"),

    url(r"^login/",views.login,name="login"),
    url(r"^logout/",views.logout,name="logout"),




]

django项目/school/school/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from forgood import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    # 代课路由
    url(r"^forclass/", include('forclass.urls', namespace="forclass")),

    #
    url(r"^forgood/", include('forgood.urls', namespace="forgood")),
    url(r"^/", views.home),
]

django项目/school/templates/usermanagement/base_user.html
{% extends 'base.html' %}
 {% load static %}

{% block ext_css %}
    <link rel="stylesheet" href="{% static 'usermanagement/css/base_user.css' %}">
{% endblock %}


{% block header %}
    <header id="header"></header>
{% endblock %}
{% block ext_js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'js/md5.js' %}"></script>
{% endblock %}

django项目/school/templates/usermanagement/login.html
{% extends 'usermanagement/base_user.html' %}
{% load static %}
{% block content %}
    {#    注册表单     #}
    <div class="container">
        <form method="post"  action="{% url 'forclass:login' %}" id="reg_form">
            {% csrf_token %}
            <p style="color: red;">{{ error_info }}</p>
            <div class="form-group">
                <label for="username_input">用户名</label>
                <input type="text" name="username" class="form-control" id="username_input" placeholder="用户名/手机号">
                <span id="username_info"></span>
            </div>
            <div class="form-group">
                <label for="passwd_input">密码</label>
                <input type="password" name="passwd" class="form-control" id="passwd_input" placeholder="请输入密码">
                <span id="passwd_info"></span>
            </div>
            <button type="submit" class="btn btn-success btn-block">登录</button>
        </form>
    </div>
{% endblock %}

{% block ext_js %}
    {% load static %}
{{ block.super }}
    <script type="text/javascript" src="{% static 'usermanagement/js/login.js' %} "></script>
{% endblock %}

django项目/school/templates/usermanagement/register.html
{% extends 'usermanagement/base_user.html' %}
{% load static %}

{% block content %}

    {#    注册表单     #}
    <div class="container">
        <form method="post" enctype="multipart/form-data" action="{% url 'forclass:register' %}" id="reg_form">
            {% csrf_token %}
            <div class="form-group">
                <label for="username_input">用户名</label>
                <input type="text" name="username" class="form-control" id="username_input" placeholder="请输入用户名">
                <span id="username_info"></span>
            </div>
            <div class="form-group">
                <label for="phone_input">手机号</label>
                <input type="text" name="phone" class="form-control" id="phone_input" placeholder="请输入手机号">
                <span id="phone_info"></span>
            </div>
            <div class="form-group">
                <label for="passwd_input">密码</label>
                <input type="password" name="passwd" class="form-control" id="passwd_input" placeholder="请输入密码">
                <span id="passwd_info"></span>
            </div>
            <div class="form-group">
                <label for="confirm_passwd_input">确认密码</label>
                <input type="password" class="form-control" id="confirm_passwd_input" placeholder="请确认密码">
                <span id="confirm_passwd_info"></span>
            </div>
            <div class="form-group">
                <label for="img_input">头像</label>
                <input type="file" name="icon" id="img_input">
            </div>
            <button type="submit" class="btn btn-success btn-block">注册</button>
        </form>
    </div>
{% endblock %}

{% block ext_js %}

    {{ block.super }}
    <script type="text/javascript" src="{% static 'usermanagement/js/register.js' %} "></script>
{% endblock %}