django项目/MovieProject/MovieProject/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^app/', include('app.urls',namespace="app")),
]

django项目/MovieProject/app/urls.py
from django.conf.urls import url

from app import views

urlpatterns = [
    # 数据准备
    url(r"^hellow/",views.hellow,name="hellow"),
    url(r"^addcarousel/",views.add_carousel,name="addcarousel"),
    url(r"^addmovies/",views.add_movies,name="addmovies"),

    # 逻辑实现
    # 主页
    url(r"^home/",views.home,name="home"),

    # 注册
    url(r"^register/",views.register,name="register"),

    # 登录
    url(r"^login/",views.login,name="login"),

    # 个人信息
    url(r"^selfinfo/",views.self_info,name="selfinfo"),

    # 刷新页面
    url(r"^myflush/",views.myflush,name="myflush"),

    # 收藏取消收藏
    url(r"^collect/",views.collect,name="collect"),

    # 个人收藏
    url(r"^selfcollect/",views.self_collect,name="selfcollect"),

    # 添加缓存
    url(r"^mycache/",views.mycache,name="mycache"),











]

django项目/MovieProject/templates/cache.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>cache</title>
</head>
<body>
<ul>
{% for c in content %}
<li>{{ c }}</li>
{% endfor %}
</ul>

</body>
</html>

django项目/MovieProject/templates/home.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    {% load static %}
    <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-theme.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/swiper.css' %}"/>
    <script type="text/javascript" src="{% static 'js/swiper.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}"/>

    <link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}"/>
    <script type="text/javascript" src="{% static 'js/home.js' %}"></script>
</head>

<body>

<div class="container-fluid box">

    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="#">fand</a>
            </div>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="{% url 'app:register' %}">注册</a>
                </li>
                <li>
                    <a href="{% url 'app:login' %}">登陆</a>
                </li>
                <!--<li>
                    <a class="icon" href="#">
                        <img width="40" height="40" class="img-circle" alt="" src="https://cs.vmovier.com/Uploads/Banner/2017/12/23/5a3d52d82724d.png" />
                    </a>
                </li>

                <li>
                    <a href=""><span>Username</span></a>
                </li>-->
            </ul>
        </div>

    </nav>

    <div class="swiper-container">
        <div class="swiper-wrapper">
            {% for carousel in carousels %}
                <div class="swiper-slide">
                    <img src="{{ carousel.c_url }}" alt="">
                </div>
            {% endfor %}

        </div>
        <!-- Add Pagination -->
        <div class="swiper-pagination swiper-pagination-white"></div>
        <!-- Add Arrows -->
        <div class="swiper-button-next swiper-button-white"></div>
        <div class="swiper-button-prev swiper-button-white"></div>
    </div>

    <ul class="nav nav-tabs child-nav">
        <li role="presentation" class="active">
            <a href="#">最新推荐</a>
        </li>
    </ul>


    <ul class="movie_list">
        {% for movie in page.object_list %}
            <li>
                <div class="movie_list_left">
                    <a target="_blank" href="{{ movie.m_more }}" title="{{ movie.m_title }}">
                        <img src="{{ movie.m_img }}" alt="{{ movie.m_title }}">
                        <div class="bottom-cover">
                            <span class="film-time">{{ movie.m_duration }}</span>
                        </div>
                    </a>
                </div>

                <div class="movie_list_right">
                    <h2>
                        <a target="_blank" href="{{ movie.m_more }}" title="{{ movie.m_title }}">
                            <span>{{ movie.m_title }}</span>
                        </a>
                    </h2>

                    <div class="movie-intro">
                        {{ movie.m_paa_fu_title }}
                    </div>
                    <div class="movie-like">
                        <span class="glyphicon glyphicon-heart" style="color: grey;"></span>
                        <span>{{ movie.m_collected }}</span>
                    </div>
                </div>
            </li>
        {% endfor %}
        <li style="margin: 50px 300px">
            <nav aria-label="Page navigation">
                <ul class="pagination">
                    {% if page.has_previous %}
                        <li>
                            <a href="{% url 'app:home' %}?page={{ page.previous_page_number }}" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                    {% else %}
                        <li class="disabled">
                            <a href="#" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                    {% endif %}
                    {% for pageNum in all_page %}
                        {% ifequal pageNum page.number %}
                             <li class="active"><a href="{% url 'app:home' %}?page={{ pageNum }}">{{ pageNum }}</a></li>
                            {% else %}
                            <li><a href="{% url 'app:home' %}?page={{ pageNum }}">{{ pageNum }}</a></li>
                        {% endifequal %}
                        {% empty %}
                        {% for p in per %}
                            {% ifequal p page.number %}
                             <li class="active"><a href="{% url 'app:home' %}?page={{ p }}">{{ p }}</a></li>
                            {% else %}
                            <li><a href="{% url 'app:home' %}?page={{ p }}">{{ p }}</a></li>
                        {% endifequal %}
                        {% endfor %}
                        <li><a href="#">……</a></li>
                        {% for l in last %}
                            {% ifequal l page.number %}
                             <li class="active"><a href="{% url 'app:home' %}?page={{ l }}">{{ l }}</a></li>
                            {% else %}
                            <li><a href="{% url 'app:home' %}?page={{ l }}">{{ l }}</a></li>
                        {% endifequal %}
                        {% endfor %}



                    {% endfor %}
                    {% if page.has_next %}
                        <li>
                            <a href="{% url 'app:home' %}?page={{ page.next_page_number }}" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                    {% else %}
                        <li class="disabled">
                            <a href="#" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                    {% endif %}

                </ul>
            </nav>
        </li>
    </ul>
</div>

</body>

</html>

django项目/MovieProject/templates/home_logined.html
<!DOCTYPE html>
<html>

	<head>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
        {% load static %}
		<script type="text/javascript" src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>
		<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" />
		<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-theme.css' %}" />
		<link rel="stylesheet" type="text/css" href="{% static 'css/swiper.css' %}" />
		<script type="text/javascript" src="{% static 'js/swiper.js' %}"></script>
		<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}" />

		<link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}"/>
		<script type="text/javascript" src="{% static 'js/home.js' %}" ></script>
	</head>

	<body>

		<div class="container-fluid" id="box">

			<nav class="navbar navbar-inverse">
				<div class="container-fluid">
					<div class="navbar-header">
						<a class="navbar-brand" href="#">Fand</a>
					</div>
					<ul class="nav navbar-nav navbar-right">
						<!--<li>
							<a href="#">注册</a>
						</li>
						<li>
							<a href="#">登陆</a>
						</li>-->
						<li>
							<a class="icon" href="{% url 'app:selfinfo' %}">
								<img width="40" height="40" class="img-circle" alt="" src="{{ icon }}" />
							</a>
						</li>

						<li>
							<a href="{% url 'app:selfinfo' %}"><span>{{ username }}</span></a>
						</li>
					</ul>
				</div>

			</nav>

			<div class="swiper-container">
				<div class="swiper-wrapper">
                {% comment %}
					<div class="swiper-slide">
						<img src="carousel.c_url" alt="">
					</div>
                {% endcomment %}

                    {% for carousel in carousels %}
                    <div class="swiper-slide">
						<img src="{{ carousel.c_url }}" alt="">
					</div>
                    {% endfor %}

				</div>
				<!-- Add Pagination -->
				<div class="swiper-pagination swiper-pagination-white"></div>
				<!-- Add Arrows -->
				<div class="swiper-button-next swiper-button-white"></div>
				<div class="swiper-button-prev swiper-button-white"></div>
			</div>

			<ul class="nav nav-tabs child-nav">
				<li role="presentation" class="active">
					<a href="{% url "app:login" %}">最新推荐</a>
				</li>
				<li role="presentation">
					<a href="{% url 'app:selfcollect' %}">收藏</a>
				</li>

			</ul>


			<ul class="movie_list">
                {% for movie in movies %}
                    <li>
					<div class="movie_list_left">
						<a target="_blank" href="{{ movie.m_more }}" title="{{ movie.m_title }}">
							<img src="{{ movie.m_img }}" alt="{{ movie.m_title }}">
							<div class="bottom-cover">
								<span class="film-time">{{ movie.m_duration }}</span>
							</div>
						</a>
					</div>

					<div class="movie_list_right">
						<h2>
							<a target="_blank" href="{{ movie.m_more }}" title="{{ movie.m_title }}">
								<span>{{ movie.m_title }}</span>
							</a>
						</h2>

						<div class="movie-intro">
							{{ movie.m_paa_fu_title }}
						</div>
						<div class="movie-like">
							<span class="glyphicon glyphicon-heart" id="xin" style="color: grey;"  postid="{{ movie.m_postid }}" ></span>
							<span>{{ movie.count }}</span>
						</div>
					</div>
				</li>
                {% endfor %}
            <span id="page">{{ movies.9.id }}</span>
			</ul>

		</div>

	</body>

</html>

django项目/MovieProject/templates/home_logined_collected.html
<!DOCTYPE html>
<html>

	<head>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
        {% load static %}
		<script type="text/javascript" src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>
		<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" />
		<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-theme.css' %}" />
		<link rel="stylesheet" type="text/css" href="{% static 'css/swiper.css' %}" />
		<script type="text/javascript" src="{% static 'js/swiper.js' %}"></script>
		<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}" />

		<link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}"/>
		<script type="text/javascript" src="{% static 'js/home.js' %}" ></script>
	</head>

	<body>

		<div class="container-fluid" id="box">

			<nav class="navbar navbar-inverse">
				<div class="container-fluid">
					<div class="navbar-header">
						<a class="navbar-brand" href="#">Fand</a>
					</div>
					<ul class="nav navbar-nav navbar-right">
						<!--<li>
							<a href="#">注册</a>
						</li>
						<li>
							<a href="#">登陆</a>
						</li>-->
						<li>
							<a class="icon" href="{% url 'app:selfinfo' %}">
								<img width="40" height="40" class="img-circle" alt="" src="{{ icon }}" />
							</a>
						</li>

						<li>
							<a href="{% url 'app:selfinfo' %}"><span>{{ username }}</span></a>
						</li>
					</ul>
				</div>

			</nav>

			<div class="swiper-container">
				<div class="swiper-wrapper">
                {% comment %}
					<div class="swiper-slide">
						<img src="carousel.c_url" alt="">
					</div>
                {% endcomment %}

                    {% for carousel in carousels %}
                    <div class="swiper-slide">
						<img src="{{ carousel.c_url }}" alt="">
					</div>
                    {% endfor %}

				</div>
				<!-- Add Pagination -->
				<div class="swiper-pagination swiper-pagination-white"></div>
				<!-- Add Arrows -->
				<div class="swiper-button-next swiper-button-white"></div>
				<div class="swiper-button-prev swiper-button-white"></div>
			</div>

			<ul class="nav nav-tabs child-nav">
				<li role="presentation" >
					<a href="#">最新推荐</a>
				</li>
				<li role="presentation" class="active">
					<a href="">收藏</a>
				</li>

			</ul>


			<ul class="movie_list">
                {% for movie in movies %}
                    <li>
					<div class="movie_list_left">
						<a target="_blank" href="{{ movie.m_more }}" title="{{ movie.m_title }}">
							<img src="{{ movie.m_img }}" alt="{{ movie.m_title }}">
							<div class="bottom-cover">
								<span class="film-time">{{ movie.m_duration }}</span>
							</div>
						</a>
					</div>

					<div class="movie_list_right">
						<h2>
							<a target="_blank" href="{{ movie.m_more }}" title="{{ movie.m_title }}">
								<span>{{ movie.m_title }}</span>
							</a>
						</h2>

						<div class="movie-intro">
							{{ movie.m_paa_fu_title }}
						</div>
						<div class="movie-like">
							<span class="glyphicon glyphicon-heart" id="xin" style="color: red;"  postid="{{ movie.m_postid }}" ></span>
							<span>{{ movie.count }}</span>
						</div>
					</div>
				</li>
                {% endfor %}
			</ul>

		</div>

	</body>

</html>

django项目/MovieProject/templates/login.html
<!DOCTYPE html>
<html>

	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
        {% load static %}
		<script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>
		<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" />
		<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-theme.css' %}" />

		<link rel="stylesheet" type="text/css" href="{% static 'css/swiper.css' %}" />
		<script type="text/javascript" src="{% static 'js/swiper.js' %}"></script>
		<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}" />
		<style type="text/css">
			.form-info {
				border: 1px solid orange;
				margin: 100px auto;
				width: 30%;
				padding: 50px;
			}
			
			.form-info h2 {
				font-size: 2rem;
				margin-bottom: 20px;
			}
			
			.form-info .submit {
				text-align: center;
			}
		</style>
	</head>

	<body>

		<div class="container-fluid">
			<div class="form-info">

				<h2>用户登陆</h2>

				<form action="{% url 'app:login' %}" method="post">
                    {% csrf_token %}
					<div class="form-group">
						<label for="exampleInputEmail1">用户名</label>
						<input type="text" name="username" class="form-control" id="exampleInputEmail1" placeholder="请输入用户名">
						<p class="help-block">请输入6-16位用户名</p>
					</div>
					<div class="form-group">
						<label for="exampleInputPassword1">密码</label>
						<input type="password" name="passwd" class="form-control" placeholder="请输入密码">
						<p class="help-block">请输入6位以上拼音字母组合密码</p>
					</div>

					<div class="submit"><button type="submit" class="btn btn-primary">登陆</button></div>

				</form>
			</div>
		</div>

	</body>

</html>

django项目/MovieProject/templates/register.html
<!DOCTYPE html>
<html>

	<head>
		<meta charset="UTF-8">
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
        {% load static %}
		<script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>
		<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" />
		<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-theme.css' %}" />

		<link rel="stylesheet" type="text/css" href="{% static 'css/swiper.css' %}" />
		<script type="text/javascript" src="{% static 'js/swiper.js' %}"></script>
		<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}" />
		<style type="text/css">
			.form-info {
				border: 1px solid orange;
				margin: 100px auto;
				width: 30%;
				padding: 50px;
			}
			
			.form-info h2{
				font-size: 2rem;
				margin-bottom: 20px;
			}
			.form-info .submit{
				text-align: center;
			}
		</style>
	</head>

	<body>

		<div class="container-fluid">
			<div class="form-info">
				
				<h2>用户注册</h2>
				
				<form action="{% url 'app:register' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
					<div class="form-group">
						<label for="exampleInputEmail1">用户名</label>
						<input type="text" name="username" class="form-control" id="exampleInputEmail1" placeholder="请输入用户名">
						<p class="help-block">请输入6-16位用户名</p>
					</div>
					<div class="form-group">
						<label for="exampleInputPassword1">密码</label>
						<input type="password" name="passwd" class="form-control" placeholder="请输入密码">
						<p class="help-block">请输入6位以上拼音字母组合密码</p>
					</div>
					<div class="form-group">
						<label for="exampleInputPassword1">确认密码</label>
						<input type="password" class="form-control" placeholder="请再次输入密码">
						<p class="help-block">请再次输入6位以上拼音字母组合密码</p>
					</div>
					<div class="form-group">
						<label for="exampleInputPassword1">邮箱</label>
						<input type="email" name="email" class="form-control" placeholder="请输入邮箱">
						<p class="help-block">请输入邮箱</p>
					</div>
					<div class="form-group">
						<label for="exampleInputFile">头像</label>
						<input type="file" name="img" id="exampleInputFile">
						
					</div>
					<div class="submit"><button type="submit" class="btn btn-primary">注册</button></div>
					
				</form>
			</div>
		</div>

	</body>

</html>

django项目/MovieProject/templates/userinfo_mod.html
<!DOCTYPE html>
<html>

	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
        {% load static %}
		<script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>
		<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" />
		<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-theme.css' %}" />

		<link rel="stylesheet" type="text/css" href="{% static 'css/swiper.css' %}" />
		<script type="text/javascript" src="{% static '' %}js/swiper.js"></script>
		<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}" />
		<style type="text/css">
			.form-info {
				border: 1px solid orange;
				margin: 100px auto;
				width: 30%;
				padding: 50px;
			}
			
			.form-info h2 {
				font-size: 2rem;
				margin-bottom: 20px;
			}
			
			.form-info .submit {
				text-align: center;
			}
			
			.form-info img{
				width: 40px;
				height: 40px;
				float: left;
			}
			input[type=file]{
				float: left;
				height: 40px;
				line-height: 40px;
				padding-left: 20px;
			}
		</style>
	</head>

	<body>

		<div class="container-fluid">
			<div class="form-info">

				<h2>信息修改</h2>

				<form action="{% url 'app:selfinfo' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
					<div class="form-group">
						<label for="exampleInputEmail1">用户名</label>
						<input type="text" class="form-control" id="exampleInputEmail1" placeholder="请输入用户名" value="{{ username }}" disabled="disabled">
					</div>
					<div class="form-group">
						<label for="exampleInputPassword1">邮箱</label>
						<input type="email" name="email" class="form-control" placeholder="请输入新的邮箱" value="旧邮箱">
					</div>
					<div class="form-group clearfix">
						<label for="exampleInputFile">头像</label><br />
						<img class="img-circle" src="{{ icon }}" alt="" />
						<input type="file" name="icon" id="exampleInputFile">
					</div>
					<div class="submit"><button type="submit" class="btn btn-primary">提交</button></div>

				</form>
			</div>
		</div>

	</body>

</html>